### ISSUE TITLE
ESPHome , Home Assistant

### ISSUE THREAD

**Issue by booroondook-eng** [orgua/OneWireHub#120]
Need to create ESPHome custom component based on OneWireHub with the following algorithm:

ESP receives temperature data from several Home Assistant's temperature sensors, and then ESP acts as set of DS18B20 for some physical receiver like heating controller etc.

**Comment by orgua** [comment]
nice, good luck! 

I don't see any issue with the codebase, so please use a forum if you need help. Will close.
