### ISSUE TITLE
DS18B20_thermometer example not work

### ISSUE THREAD

**Issue by maxibons** [orgua/OneWireHub#21]
Use ide 1.6.13 and UNO-board.
DS18B20_thermometer (original) compiles without errors.
But in serial port waste comes.

**Comment by orgua** [comment]
it seems like a basic arduino-misconfig - you can check these two things: 
- do you already compile for the uno or another board?
- does your serial console run at 115200 baud? the example is configured this way

**Comment by maxibons** [comment]
only UNO.
Thanks.
With it
`void setup()
{
    Serial.begin(9600);`
work!

**Comment by orgua** [comment]
yeah, not recommended but possible. have fun playing with it
