### ISSUE TITLE
DS2408 example pin 7 assignment collides with GPIO_DEBUG_PIN

### ISSUE THREAD

**Issue by ecnelson** [orgua/OneWireHub#30]
The DS2408 example assigns PIO pin 7 to Arduino pin 7; however, GPIO_DEBUG_PIN is also assigned to Arduino pin 7. It's a good set of mnemonic pin assignments in the example (10, 11, 2–7 for P0–P7) so perhaps it would be best to reassign the GPIO_DEBUG_PIN in OneWireHub_config.h

**Comment by orgua** [comment]
ok, should be fixed for a long time now, will close
