### ISSUE TITLE
Building the project

### ISSUE THREAD

**Issue by cwrseck** [orgua/OneWireHub#53]
Is there any documentation anywhere on how to build the project?
I tried opening the directory with the current Arduino IDE, but it
didn't recognise any files, and I couldn't find a Makefile alternative.

Thanks - Will

**Comment by orgua** [comment]
did you improve on your arduino-skills yet? 
- "any"-file seems a bit harsh, there are at least *.ino-files that your IDE understands
- what kind of makefile alternatives do you know? The is cmake right in the main-directory
