### ISSUE TITLE
Does DS2431 support skip command?

### ISSUE THREAD

**Issue by x225am** [orgua/OneWireHub#92]
I checked DS2431.cpp and looks like there are no support for SKIP ROM [CCh] and for READ ROM [33h] commands. Is anyone have implemented it?

**Comment by orgua** [comment]
These are general Onewire-Functions, essential for basic operations - so they are in the base class. Have a look at 
https://github.com/orgua/OneWireHub/blob/master/src/OneWireHub.cpp#L480

The projects readme.md also states this under "features", third entry in  
https://github.com/orgua/OneWireHub/blob/master/README.md
