### ISSUE TITLE
DS2431 Difference behavior between real eeprom and arduino emulator

### ISSUE THREAD

**Issue by x225am** [orgua/OneWireHub#93]
Hi all, I have some devices with DS2431 eeprom I have read all info from it  loaded in to the Arduino eeprom emulator. For some reason when I trying use this emulator in the real device it just would not accept it. I read with logic analayzer packets between master and eeprom and compare them with emulator. For some reason emulator would not respond on requests.
Please have a look screens from the Analayzer:
This is from original DS2431 eeprom
![Ashampoo_Snap_Sunday, 6 December 2020_22h59m06s_001_](https://user-images.githubusercontent.com/42084385/101279489-c033fa80-3816-11eb-84c8-59932d463296.png)
And this one is from emulated. For some reason it only reset packets.
![Ashampoo_Snap_Sunday, 6 December 2020_23h01m23s_003_](https://user-images.githubusercontent.com/42084385/101279526-fec9b500-3816-11eb-8f82-94d2d1d137cb.png)

**Comment by orgua** [comment]
cool that you have the needed tools and interest in getting this to run. unfortunately your screenshot does not tell much. its 99% a timing-problem (as usual). Well, i can only give you the same answer as yesterday: please read through the main readme. There is a dedicated help-section

https://github.com/orgua/OneWireHub/blob/master/README.md

**Comment by orgua** [comment]
(feel free to reopen if there is a real bug)
